# Generated by Django 3.2.5 on 2021-07-18 08:18

from django.db import migrations, models
import django_countries.fields



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='First Name', max_length=255)),
                ('mobile', models.CharField(help_text='Mobile', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
            ],
        ),
    ]
