# Generated by Django 3.2.5 on 2021-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='mobile',
        ),
    ]
