# Generated by Django 3.2.5 on 2021-07-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0003_shareholder_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(help_text='Duration in years')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_type', models.IntegerField(choices=[('Monthly', 1), ('Quarterly', 2), ('Annual', 3)])),
                ('start_date', models.DateField()),
                ('shareholder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shareholder.shareholder')),
            ],
        ),
    ]
